### ISSUE TITLE
Handle extra underscores around variables

### ISSUE THREAD

**Issue by diego-codes** [yuanhjty/code-template-tool#1]
Hi there! First, that you so much for this extension it's a time saver! I'm running into the following issue:

### Expected behavior
Sass relies on the`_file-name.scss` naming pattern for identifying files that should output a css file. I was trying to auto generate file names and imports with this naming convention in mind:

```json
// template.config.json
{
  "name": "React Component",
  "variables": ["componentName"]
}
```

Then I attempted to create a scss file with an extra _ in the name to be included in the file name: `____component-name___.scss` to create `_react-component.scss`.

I also imported this file into a JS file:
```js
// index.js
import './____component-name___.scss'; // -> import './_react-component.scss';
```

I expected that any additional underscores (_) would be respected and remain unchanged.

### Actual behavior
All extra underscores (_) are replaced with the variable string:

`____component-name___.scss` creates `react-component.scss`

And

```js
// index.js
import './____component-name___.scss'; // -> import './react-component.scss';
```

**Comment by yuanhjty** [comment]
@diego-codes I am so sorry for my late reply. Prefix and suffix underscores are not supported yet. Thanks you for your reminding, I will add support for prefix and suffix underscores in next version (expected to be released next week).

**Comment by yuanhjty** [comment]
@diego-codes  Code Template Tool v0.2.0 supports prefix and suffix underscores with config like this:
```
// template.config.json
{
  "name": "React Component",
  "variables": [
    {
      "name": "componentName",
      "prefixUnderscore": 1,
      "suffixUnderscore": 2
    }
  ]
}
```

**Comment by diego-codes** [comment]
Great! Thank you!! Will check it out.
