### ISSUE TITLE
about codeTemplateTool.templatesPath 

### ISSUE THREAD

**Issue by caohaijiang** [yuanhjty/code-template-tool#2]
在vscode的首选项中找不到
Not found in vscode's preferences

**Comment by yuanhjty** [comment]
打开 settings.json 添加 codeTemplateTool.templatesPath
```json
{
    "codeTemplateTool.templatesPath": "/path/to/templates"
}
```

**Comment by caohaijiang** [comment]
@yuanhjty 又体验了一下mac os 中使用这个插件: 
codeTemplateTool.templatesPath"  这个路径设置为 ~ 用户目录下有问题, 设置了绝对路径也没有找到. 都提示mkdir创建这个目录, 是否在mac中解析路径有问题呢?

**Comment by yuanhjty** [comment]
之前的版本不支持对 ~ 的解析，也不支持递归创建目录。我刚发布了新版本，其中增加了对上述两个特性的支持。
