### ISSUE TITLE
Base folder doesn't get created

### ISSUE THREAD

**Issue by siddharth-golchha** [yuanhjty/code-template-tool#20]
I configured the extension as mentioned in the documentation. The only setting I have overwritten is the Template Path to use `{workspace}/templates`.
This is how one of my template looks - 
```
+ ___component-name___
    - ___component-name___.component.tsx
    - ___component-name___.module.scss
    - ___component-name___.interfaces.ts
    - index.ts
```
The problems I encountered are - 
1. It doesn't generate the base folder as per `+ ___component-name___`. It just generates all the files directly inside the directory I invoked this command on. I right click on a directory and select "New File/Folder from template". I would expect it to 1st generate the base directory and then create all files inside that directory. As you can check in the attached screenshot, the template didn't create the base directory, but generated all the files directly inside "components" folder.
<img width="287" alt="Screen Shot 2020-03-27 at 7 39 10 PM" src="https://user-images.githubusercontent.com/3908077/77813032-a674cd80-7062-11ea-9267-84bf5463d4f6.png">
2. It generates an extra "template" file along with other files. Is this intentional? Can I add a setting to not generate this file?

I am using VSCode Version: 1.43.1 & latest version of this extension.
Thanks for the help.

**Comment by yuanhjty** [comment]
@siddharth-golchha Sorry for late response. Your template should be like this:
```
+ template-dir
   + ___component-name___
      - ___component-name___.component.tsx
      - ___component-name___.module.scss
      - ___component-name___.interfaces.ts
      - index.ts
   - template.config.json
```

See docs about template structure
```
+ exampleTemplate               // template define folder
   - template.config.json       // template configuration file
   - {other files and folders}  // template content
```
