### ISSUE TITLE
[BUG] No any things shown in editor when selected template

### ISSUE THREAD

**Issue by chenxxzhe** [yuanhjty/code-template-tool#23]
VSCODE version:
```
版本: 1.47.1
提交: 485c41f9460bdb830c4da12c102daff275415b53
日期: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.2.0
```

![image](https://user-images.githubusercontent.com/9720961/87523145-20d06880-c6b9-11ea-8c7e-6910558e3463.png)

**Comment by disbelief** [comment]
Same behaviour for me. Was working till the latest VS Code update. Something in the latest version of VS Code seems to have broken this extension.

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by RickR2H** [comment]
@yuanhjty Same issue here! Updating to VScode latest version breaks the extension. It looks like the popup is blocked.

**Comment by juanrb** [comment]
Same here, I use this extension all the time, it's awesome... Please fix it!

**Comment by yuanhjty** [comment]
I'm sorry, I was too busy recently.  I will fix it this week.

**Comment by RickR2H** [comment]
> I'm sorry, I was too busy recently. I will fix it this week.

No sorry please! We are all happy users of your great and FREE extension. Thanks for taking time to fix the issue!

**Comment by roggenbrot** [comment]
Workaround:

1. Open file .vscode/extensions/yuanhjty.code-template-tool-0.6.1/out/worker/getUserInput.js
2. Replace 
```
panel.webview.html = getWebviewContent(templateName, userInputRequest, resolveUri);
```

with

```
const resolveUriFix = (diskPath) =>{
   		const diskUri = vscode_1.Uri.file(path_1.resolve(extensionContext.extensionPath, diskPath));
        	return panel.webview.asWebviewUri(diskUri);
}
panel.webview.html = getWebviewContent(templateName, userInputRequest, resolveUriFix);
```

**Comment by yuanhjty** [comment]
The problem has been fixed, please upgrade your extension.

**Comment by juanrb** [comment]
> The problem has been fixed, please upgrade your extension.

Thanks man!

**Comment by disbelief** [comment]
Thanks @yuanhjty for writing this extension and for continuing to support it. You have saved me thousands of keystrokes!
