### ISSUE TITLE
Options for Context Menus

### ISSUE THREAD

**Issue by naegling** [yuanhjty/code-template-tool#34]
Very convenient and configurable tool.  Thanks!
I would like to request the ability to select which menu options are included in the context menu.  "Edit Templates" and "Reload Templates" should rarely be used and I would prefer they only be accessible from the command palette or keyboard shortcut.

**Comment by SjaaLom** [comment]
I second that motion. I love the tool and as a general suggestion, the contextmenu could do with a little cleanup. Should not even have to be configurable. I would be okay with it if I had to use the command palette for the lesser used functions.
Thank you!

**Comment by yuanhjty** [comment]
Agree with you, "Edit Templates" and "Reload Templates" has been removed from the context menu in v0.6.3.
