### ISSUE TITLE
Broken in vscode version 1.56

### ISSUE THREAD

**Issue by stefanpl** [yuanhjty/code-template-tool#39]
The plugin is not working since the upgrade to [vscode `1.56`](https://code.visualstudio.com/updates/v1_56). All I see when trying to create file/folder from template is an empty white input:

![image](https://user-images.githubusercontent.com/2606570/117789045-3c0ff400-b248-11eb-9b91-f59066b85f2a.png)

Verified by [downgrading to 1.55](https://code.visualstudio.com/updates/v1_55), where everything's working fine.

If you need more information to replicate, please let me know.

Thanks a lot in advance for taking a look 🙏

**Comment by rikjacobs1390** [comment]
Same!

**Comment by RickR2H** [comment]
Just a message to confirm the issue too. Hope the dev will find some time to fix the issue.

**Comment by pro100andrey** [comment]
Some

**Comment by nitpum** [comment]
Same

**Comment by nicholasxuu** [comment]
Same

**Comment by stefanpl** [comment]
@yuanhjty could you please give us any insights regarding to this? Me and my team use the plugin quite heavily, and while it's not a showstopper to not have it, it certainly feels like a drag.

I'd be very happy if you could tell me:
- have you already been able to take a look at the issue?
- will you be able to fix it yourself any time soon?

If you're not available at the moment, I think we can all fully understand. Then:
- would you at least be willing to check and merge a PR for this?
- do you have an estimation of the complexity to fix it? I've never done anything with vscode plugins 😳

**Comment by RickR2H** [comment]
> Sorry for my late reply, I 'll fix it it weekend.

Great!!!! ;)

**Comment by yuanhjty** [comment]
Fixed, please update to v0.6.3.

**Comment by SjaaLom** [comment]
Thx!
