### ISSUE TITLE
[feature]: Could you support default value of variables?

### ISSUE THREAD

**Issue by chenxxzhe** [yuanhjty/code-template-tool#4]
for example, add `default` field in `variables`
```
"variables": [
        {
            "name": "abcDef",
            "case": "camelCase",
            "prefixUnderscore": 3,
            "default": "defaultValue"
        }
]
```

`___abcDef___`  will compile to  `defaultValue`  when `abcDef` is empty

#5

**Comment by yuanhjty** [comment]
@chenxxzhe Default value of variables has been supported in newly released V0.3.0.
