### ISSUE TITLE
Feature requests - user flow

### ISSUE THREAD

**Issue by ruudvanham** [yuanhjty/code-template-tool#9]
Thanks for the great work. Currently I'm setting up your plugin inside our project workflow and i've got some feature requests to make it even better.

- If only one template available, directly select it and go to edit page
- On edit page, focus directly to first (var) input field 
- Submit on enter

This way we can limit the use of a mouse and quickly add templates with vars inside our projects.

**Comment by yuanhjty** [comment]
@ruudvanham You are right. I will implement the features later.

**Comment by yuanhjty** [comment]
@ruudvanham The features your mentioned is now supported in v0.5.0, see the docs.
